version: '3.8'

services:
  oracle-db:
    build:
      context: ./database
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - oracle-db
    environment:
      - DB_USER=project_user
      - DB_PASSWORD=project_password
      - DB_CONNECTIONSTRING=oracle-db:1521/XE

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
